import streamlit as st
import pandas as pd
import json
import plotly.graph_objects as go
import plotly.express as px # Import for bar chart
from collections import defaultdict

# --- Configuration ---
# Use the JSON generated by the v2 script, which includes processed_urls
SCORES_JSON_PATH = "./hifi_product_scores.json"
# ORIGINAL_DATA_JSON_PATH = "/home/ubuntu/upload/top_10_result.json" # No longer needed for URLs
TOP_N_FEATURES_RADAR = 5

# --- Data Loading and Preparation ---
@st.cache_data # Cache the data loading
def load_scores_data(scores_path):
    """Loads scores data which now includes processed URLs."""
    try:
        with open(scores_path, 'r', encoding='utf-8') as f:
            scores_data = json.load(f)
        print(f"Loaded scores from: {scores_path}")

        # Ensure product name is not empty for display
        for product_id, data in scores_data.items():
            if not data.get('product_name'):
                data['product_name'] = f"Product ID: {product_id[:8]}..." # Use partial ID if name is missing
            # Ensure processed_urls exists, even if empty
            if 'processed_urls' not in data:
                data['processed_urls'] = []
        return scores_data

    except FileNotFoundError:
        st.error(f"Error: Scores file not found at {scores_path}")
        return None
    except json.JSONDecodeError:
        st.error(f"Error: Could not decode JSON from {scores_path}")
        return None

# --- Streamlit App Layout ---
st.set_page_config(page_title="HiFi Review Analysis", layout="wide")
st.title("HiFi Audio Product Review Analysis")

# Load the data
data = load_scores_data(SCORES_JSON_PATH)

if data:
    product_names = {pid: pdata.get("product_name", f"Unknown ID: {pid}") for pid, pdata in data.items()}
    # Sort products by name for the dropdown
    sorted_product_ids = sorted(product_names, key=lambda pid: product_names[pid])

    # --- Sidebar for Product Selection ---
    st.sidebar.header("Select Product")
    selected_product_id = st.sidebar.selectbox(
        "Choose a product:",
        options=sorted_product_ids,
        format_func=lambda pid: product_names[pid] # Show product name in dropdown
    )

    # --- Main Panel Display ---
    if selected_product_id:
        product_data = data[selected_product_id]
        product_name = product_data.get("product_name", "N/A")
        overall_score = product_data.get("final_score_100", 0)
        # Use the accurate review_count from the JSON
        review_count = product_data.get("review_count", 0)
        feature_scores = product_data.get("feature_scores_100", {})
        # Use the processed_urls list from the JSON
        processed_urls = product_data.get("processed_urls", [])

        st.header(f"{product_name}")
        st.metric(label="Overall Score", value=f"{overall_score:.1f}/100")
        # Display the accurate review count
        st.caption(f"Based on {review_count} processed reviews.")

        col1, col2 = st.columns(2)

        with col1:
            st.subheader("Top Feature Scores (Radar)")
            # --- Radar Chart (Top N Features) ---
            if feature_scores:
                sorted_features_radar = sorted(feature_scores.items(), key=lambda item: item[1], reverse=True)
                top_features = dict(sorted_features_radar[:TOP_N_FEATURES_RADAR])

                if top_features:
                    categories = [f.capitalize() for f in top_features.keys()]
                    scores_radar = list(top_features.values())

                    fig_radar = go.Figure()
                    fig_radar.add_trace(go.Scatterpolar(
                        r=scores_radar,
                        theta=categories,
                        fill='toself',
                        name='Score'
                    ))
                    fig_radar.update_layout(
                        polar=dict(radialaxis=dict(visible=True, range=[0, 100])),
                        showlegend=False,
                        title=f"Top {len(categories)} Features"
                    )
                    st.plotly_chart(fig_radar, use_container_width=True)
                else:
                    st.write("No significant feature scores found for radar chart.")
            else:
                st.write("Feature scores not available.")

        with col2:
            st.subheader("All Feature Scores (Bar)")
            # --- Bar Chart (All Features) (Step 008) ---
            if feature_scores:
                # Sort all features by score for the bar chart
                sorted_features_bar = sorted(feature_scores.items(), key=lambda item: item[1], reverse=True)
                features_bar = [item[0].capitalize() for item in sorted_features_bar]
                scores_bar = [item[1] for item in sorted_features_bar]

                fig_bar = px.bar(
                    x=scores_bar,
                    y=features_bar,
                    orientation='h', # Horizontal bar chart
                    title="All Feature Scores",
                    labels={'x': 'Score (0-100)', 'y': 'Feature'},
                    text=scores_bar # Add score labels to bars
                )
                fig_bar.update_layout(
                    yaxis={'categoryorder':'total ascending'}, # Keep highest score at top
                    xaxis_range=[0,100]
                )
                fig_bar.update_traces(texttemplate='%{text:.1f}', textposition='outside')
                st.plotly_chart(fig_bar, use_container_width=True)
            else:
                st.write("Feature scores not available for bar chart.")


        # --- Review URLs (Corrected - Step 009) ---
        st.subheader("Review URLs Considered")
        if processed_urls:
            # Display the URLs from the processed_urls list
            for url in processed_urls:
                st.markdown(f"- [{url}]({url})")
        else:
            st.write("No review URLs were processed for this product (or URLs were not available).")

else:
    st.error("Failed to load analysis data. Cannot display application.")

